# Threshold distance - how much each joint can be away from predefined position
max_distance_rad: 0.35 # about 20 degrees

# Time [in seconds] after which goal is aborted if no keep_alive message is received
stop_trajectory_timeout: 0.5

# Predefined poses. Path has to be relative to kalman_arm_config package
poses:
  - name: "base"
    path: "predefined_poses/move_group_goal.yaml"
  - name: "left_base"
    path: "predefined_poses/left_base.yaml"