# Threshold distance - how much each joint can be away from predefined position
max_distance_rad: 0.35 # about 20 degrees

# Time [in seconds] after which goal is aborted if no keep_alive message is received
stop_trajectory_timeout: 1.5

# Predefined poses. Path has to be relative to kalman_arm_config package
# ID must correspond to value in ArmPoseSelect message
poses:
  - id: 0
    name: "base"
    path: "predefined_poses/move_group_goal.yaml"
    joints_set: ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
    joints_checked: ["joint_1", "joint_2", "joint_3"]
  - id: 1
    name: "left_base"
    path: "predefined_poses/left_base.yaml"
    joints_set: ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
    joints_checked: ["joint_1", "joint_2", "joint_3"]
  - id: 2
    name: "reset_4_and_6"
    path: "predefined_poses/reset.yaml"
    joints_set: ["joint_4", "joint_6"]
    joints_checked: []
