imu_filter_madgwick:
  ros__parameters:
    stateless: false
    use_mag: true
    publish_tf: false
    reverse_tf: false
    fixed_frame: "odom"
    constant_dt: 0.0
    remove_gravity_vector: false
    publish_debug_topics: false
    yaw_offset: 0.0
    declination: 0.0 # After testing and ocmparing with Google Maps, I'm convinced that Phidgets Spatial automatically corrects for declination. 
    world_frame: "enu"
    gain: 0.05 # NOTE: Smaller value turned out to work better with the UKF.
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 1.0
    use_sim_time: false
