/**:
  ros__parameters:
    # Image transport for color images.
    color_transport: compressed
    # Image transport for depth images.
    depth_transport: compressedDepth
    # Horizontal resolution of the point cloud.
    cloud_width: 160
    # Minimum distance of a point to be included in the point cloud.
    min_distance: 0.1
    # Maximum distance of a point to be included in the point cloud.
    max_distance: 5.0
