# MANIPULATOR

link_1_controller:
    type: effort_controllers/JointPositionController
    joint: link_1_joint
    pid:
        {
            p: 1000.0,
            i: 100.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

link_2_controller:
    type: effort_controllers/JointPositionController
    joint: link_2_joint
    pid:
        {
            p: 1000.0,
            i: 200.0,
            d: 10.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

link_3_controller:
    type: effort_controllers/JointPositionController
    joint: link_3_joint
    pid:
        {
            p: 1000.0,
            i: 100.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

link_4_controller:
    type: effort_controllers/JointPositionController
    joint: link_4_joint
    pid:
        {
            p: 1000.0,
            i: 100.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

link_5_controller:
    type: effort_controllers/JointPositionController
    joint: link_5_joint
    pid:
        {
            p: 1000.0,
            i: 100.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

grip_0_controller:
    type: effort_controllers/JointPositionController
    joint: grip_0_joint
    pid:
        {
            p: 1000.0,
            i: 100.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

grip_1_controller:
    type: effort_controllers/JointPositionController
    joint: grip_1_joint
    pid:
        {
            p: 1000.0,
            i: 100.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }
