drilling_frame_controller:
    type: effort_controllers/JointPositionController
    joint: drilling_frame_joint
    pid:
        {
            p: 1000.0,
            i: 200.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

drilling_module_controller:
    type: effort_controllers/JointPositionController
    joint: drilling_module_joint
    pid:
        {
            p: 8000.0,
            i: 260.0,
            d: 140.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

probing_module_controller:
    type: effort_controllers/JointPositionController
    joint: probing_module_joint
    pid:
        {
            p: 4000.0,
            i: 100.0,
            d: 50.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

drill_controller:
    type: effort_controllers/JointVelocityController
    joint: drill_joint
    pid:
        {
            p: 10.0,
            i: 10.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }
