joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

propulsion_module_fl_controller:
    type: effort_controllers/JointPositionController
    joint: propulsion_module_fl_joint
    pid:
        {
            p: 2000.0,
            i: 300.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

propulsion_module_fr_controller:
    type: effort_controllers/JointPositionController
    joint: propulsion_module_fr_joint
    pid:
        {
            p: 2000.0,
            i: 300.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

propulsion_module_bl_controller:
    type: effort_controllers/JointPositionController
    joint: propulsion_module_bl_joint
    pid:
        {
            p: 2000.0,
            i: 300.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

propulsion_module_br_controller:
    type: effort_controllers/JointPositionController
    joint: propulsion_module_br_joint
    pid:
        {
            p: 2000.0,
            i: 300.0,
            d: 20.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

wheel_fl_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_fl_joint
    pid:
        {
            p: 100.0,
            i: 50.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

wheel_fr_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_fr_joint
    pid:
        {
            p: 100.0,
            i: 50.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

wheel_bl_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_bl_joint
    pid:
        {
            p: 100.0,
            i: 50.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

wheel_br_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_br_joint
    pid:
        {
            p: 100.0,
            i: 50.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }

lidar_tower_controller:
    type: effort_controllers/JointVelocityController
    joint: lidar_tower_joint
    pid:
        {
            p: 1.0,
            i: 0.0,
            d: 0.0,
            i_clamp_min: 0.0,
            i_clamp_max: 0.0,
            antiwindup: True,
        }
