yolo_detect:
  ros__parameters:
    # Queue size for image subscriptions and detection publisher.
    queue_size: 10
    # Use approximate time synchronization for color and depth topics. Each camera is synchronized separately.
    approx_sync: false
    # List of compressed color topics to subscribe to.
    compressed_color_topics:
    - /d455_front/color/image_raw/compressed
    # List of compressed depth topics to subscribe to.
    # compressed_depth_topics:
    # - /d455_front/aligned_depth_to_color/image_raw/compressed
    # List of camera info topics to subscribe to. Both color and depth cameras must share the same intrinsics.
    camera_info_topics:
    - /d455_front/color/camera_info
    # Detection frequency in Hz.
    frequency: 10.0
    # Path to YOLO model weights in PT format.
    model: $(find-pkg-share kalman_yolo)/models/urc2024/1698670825.pt
    # List of class names.
    classes:
    - widemouth
    - mallet
    # Average real life half-width of each class in meters. Used to find the 3D position of detections, but only needed if depth topics are unavailable.
    fallback_class_radii:
    - 0.15
    - 0.15
    # Detection threshold.
    threshold: 0.7
    # Number of history frames to use for temporal filtering. Set to 0 for no smoothing and no ID tracking.
    temporal_window: 10
    # Number of times a detection must be present in the history to pass through the filter.
    # Must be less than or equal to temporal_window. Setting it to 0 will disable entry
    # filtering and setting it to temporal_window value will disable exit filtering.
    # Entry filtering is useful for preventing false positives from being reported,
    # while exit filtering is useful for preventing existing detections from jumping around and disappearing.
    # Theoretically, the optimal temporal_threshold is temporal_window / 2.
    temporal_threshold: 5
    # Maximum 3D distance between two detections of the same class to consider them the same.
    merge_radius: 0.5
    # Default depth of a detection if depth information and class radii are for some reason unavailable.
    fallback_z: 2
    # Annotate images with detection results and publish them to /yolo_detect/annotated{i}/image_raw/compressed.
    annotate: true
    # Publish detection results as visualization_msgs/MarkerArray on /yolo_detect/markers.
    publish_markers: true