services:
  demo:
  kml:
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: gm_layer
    title: Test of using GM tiles
    sources: [gm_cache]

caches:
  gm_cache:
    grids: [gm_grid]
    sources: [gm]
    cache:
      type: file
      directory_layout: tms

sources:
  gm:
    # https://github.com/danielsnider/docker-mapproxy-googlemaps
    type: tile
    url: http://mt0.google.com/vt/lyrs=s@0&hl=en&x=%(x)s&y=%(y)s&z=%(z)s
    grid: gm_grid

grids:
  gm_grid:
    base: GLOBAL_MERCATOR
    origin: ul
