controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 25 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # imu_broadcaster:
    #   type: imu_sensor_broadcaster/IMUSensorBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - wheel_fl_joint
      - wheel_fr_joint
      - wheel_bl_joint
      - wheel_br_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - propulsion_module_fl_joint
      - propulsion_module_fr_joint
      - propulsion_module_bl_joint
      - propulsion_module_br_joint
      - rocker_l_joint
      - rocker_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position